const countries = [
  {
    code: "AF",
    code3: "AFG",
    country_name: "Afghanistan",
    country_number: "004",
  },
  { code: "AL", code3: "ALB", country_name: "Albania", country_number: "008" },
  { code: "DZ", code3: "DZA", country_name: "Algeria", country_number: "012" },
  {
    code: "AS",
    code3: "ASM",
    country_name: "American Samoa",
    country_number: "016",
  },
  { code: "AD", code3: "AND", country_name: "Andorra", country_number: "020" },
  { code: "AO", code3: "AGO", country_name: "Angola", country_number: "024" },
  { code: "AI", code3: "AIA", country_name: "Anguilla", country_number: "660" },
  {
    code: "AQ",
    code3: "ATA",
    country_name: "Antarctica",
    country_number: "010",
  },
  {
    code: "AG",
    code3: "ATG",
    country_name: "Antigua and Barbuda",
    country_number: "028",
  },
  {
    code: "AR",
    code3: "ARG",
    country_name: "Argentina",
    country_number: "032",
  },
  { code: "AM", code3: "ARM", country_name: "Armenia", country_number: "051" },
  { code: "AW", code3: "ABW", country_name: "Aruba", country_number: "533" },
  {
    code: "AU",
    code3: "AUS",
    country_name: "Australia",
    country_number: "036",
  },
  { code: "AT", code3: "AUT", country_name: "Austria", country_number: "040" },
  {
    code: "AZ",
    code3: "AZE",
    country_name: "Azerbaijan",
    country_number: "031",
  },
  {
    code: "BS",
    code3: "BHS",
    country_name: "Bahamas (the)",
    country_number: "044",
  },
  { code: "BH", code3: "BHR", country_name: "Bahrain", country_number: "048" },
  {
    code: "BD",
    code3: "BGD",
    country_name: "Bangladesh",
    country_number: "050",
  },
  { code: "BB", code3: "BRB", country_name: "Barbados", country_number: "052" },
  { code: "BY", code3: "BLR", country_name: "Belarus", country_number: "112" },
  { code: "BE", code3: "BEL", country_name: "Belgium", country_number: "056" },
  { code: "BZ", code3: "BLZ", country_name: "Belize", country_number: "084" },
  { code: "BJ", code3: "BEN", country_name: "Benin", country_number: "204" },
  { code: "BM", code3: "BMU", country_name: "Bermuda", country_number: "060" },
  { code: "BT", code3: "BTN", country_name: "Bhutan", country_number: "064" },
  {
    code: "BO",
    code3: "BOL",
    country_name: "Bolivia (Plurinational State of)",
    country_number: "068",
  },
  {
    code: "BQ",
    code3: "BES",
    country_name: "Bonaire, Sint Eustatius and Saba",
    country_number: "535",
  },
  {
    code: "BA",
    code3: "BIH",
    country_name: "Bosnia and Herzegovina",
    country_number: "070",
  },
  { code: "BW", code3: "BWA", country_name: "Botswana", country_number: "072" },
  {
    code: "BV",
    code3: "BVT",
    country_name: "Bouvet Island",
    country_number: "074",
  },
  { code: "BR", code3: "BRA", country_name: "Brazil", country_number: "076" },
  {
    code: "IO",
    code3: "IOT",
    country_name: "British Indian Ocean Territory (the)",
    country_number: "086",
  },
  {
    code: "BN",
    code3: "BRN",
    country_name: "Brunei Darussalam",
    country_number: "096",
  },
  { code: "BG", code3: "BGR", country_name: "Bulgaria", country_number: "100" },
  {
    code: "BF",
    code3: "BFA",
    country_name: "Burkina Faso",
    country_number: "854",
  },
  { code: "BI", code3: "BDI", country_name: "Burundi", country_number: "108" },
  {
    code: "CV",
    code3: "CPV",
    country_name: "Cabo Verde",
    country_number: "132",
  },
  { code: "KH", code3: "KHM", country_name: "Cambodia", country_number: "116" },
  { code: "CM", code3: "CMR", country_name: "Cameroon", country_number: "120" },
  { code: "CA", code3: "CAN", country_name: "Canada", country_number: "124" },
  {
    code: "KY",
    code3: "CYM",
    country_name: "Cayman Islands (the)",
    country_number: "136",
  },
  {
    code: "CF",
    code3: "CAF",
    country_name: "Central African Republic (the)",
    country_number: "140",
  },
  { code: "TD", code3: "TCD", country_name: "Chad", country_number: "148" },
  { code: "CL", code3: "CHL", country_name: "Chile", country_number: "152" },
  { code: "CN", code3: "CHN", country_name: "China", country_number: "156" },
  {
    code: "CX",
    code3: "CXR",
    country_name: "Christmas Island",
    country_number: "162",
  },
  {
    code: "CC",
    code3: "CCK",
    country_name: "Cocos (Keeling) Islands (the)",
    country_number: "166",
  },
  { code: "CO", code3: "COL", country_name: "Colombia", country_number: "170" },
  {
    code: "KM",
    code3: "COM",
    country_name: "Comoros (the)",
    country_number: "174",
  },
  {
    code: "CD",
    code3: "COD",
    country_name: "Congo (the Democratic Republic of the)",
    country_number: "180",
  },
  {
    code: "CG",
    code3: "COG",
    country_name: "Congo (the)",
    country_number: "178",
  },
  {
    code: "CK",
    code3: "COK",
    country_name: "Cook Islands (the)",
    country_number: "184",
  },
  {
    code: "CR",
    code3: "CRI",
    country_name: "Costa Rica",
    country_number: "188",
  },
  { code: "HR", code3: "HRV", country_name: "Croatia", country_number: "191" },
  { code: "CU", code3: "CUB", country_name: "Cuba", country_number: "192" },
  { code: "CW", code3: "CUW", country_name: "Curaçao", country_number: "531" },
  { code: "CY", code3: "CYP", country_name: "Cyprus", country_number: "196" },
  { code: "CZ", code3: "CZE", country_name: "Czechia", country_number: "203" },
  {
    code: "CI",
    code3: "CIV",
    country_name: "Côte d'Ivoire",
    country_number: "384",
  },
  { code: "DK", code3: "DNK", country_name: "Denmark", country_number: "208" },
  { code: "DJ", code3: "DJI", country_name: "Djibouti", country_number: "262" },
  { code: "DM", code3: "DMA", country_name: "Dominica", country_number: "212" },
  {
    code: "DO",
    code3: "DOM",
    country_name: "Dominican Republic (the)",
    country_number: "214",
  },
  { code: "EC", code3: "ECU", country_name: "Ecuador", country_number: "218" },
  { code: "EG", code3: "EGY", country_name: "Egypt", country_number: "818" },
  {
    code: "SV",
    code3: "SLV",
    country_name: "El Salvador",
    country_number: "222",
  },
  {
    code: "GQ",
    code3: "GNQ",
    country_name: "Equatorial Guinea",
    country_number: "226",
  },
  { code: "ER", code3: "ERI", country_name: "Eritrea", country_number: "232" },
  { code: "EE", code3: "EST", country_name: "Estonia", country_number: "233" },
  { code: "SZ", code3: "SWZ", country_name: "Eswatini", country_number: "748" },
  { code: "ET", code3: "ETH", country_name: "Ethiopia", country_number: "231" },
  {
    code: "FK",
    code3: "FLK",
    country_name: "Falkland Islands (the) [Malvinas]",
    country_number: "238",
  },
  {
    code: "FO",
    code3: "FRO",
    country_name: "Faroe Islands (the)",
    country_number: "234",
  },
  { code: "FJ", code3: "FJI", country_name: "Fiji", country_number: "242" },
  { code: "FI", code3: "FIN", country_name: "Finland", country_number: "246" },
  { code: "FR", code3: "FRA", country_name: "France", country_number: "250" },
  {
    code: "GF",
    code3: "GUF",
    country_name: "French Guiana",
    country_number: "254",
  },
  {
    code: "PF",
    code3: "PYF",
    country_name: "French Polynesia",
    country_number: "258",
  },
  {
    code: "TF",
    code3: "ATF",
    country_name: "French Southern Territories (the)",
    country_number: "260",
  },
  { code: "GA", code3: "GAB", country_name: "Gabon", country_number: "266" },
  {
    code: "GM",
    code3: "GMB",
    country_name: "Gambia (the)",
    country_number: "270",
  },
  { code: "GE", code3: "GEO", country_name: "Georgia", country_number: "268" },
  { code: "DE", code3: "DEU", country_name: "Germany", country_number: "276" },
  { code: "GH", code3: "GHA", country_name: "Ghana", country_number: "288" },
  {
    code: "GI",
    code3: "GIB",
    country_name: "Gibraltar",
    country_number: "292",
  },
  { code: "GR", code3: "GRC", country_name: "Greece", country_number: "300" },
  {
    code: "GL",
    code3: "GRL",
    country_name: "Greenland",
    country_number: "304",
  },
  { code: "GD", code3: "GRD", country_name: "Grenada", country_number: "308" },
  {
    code: "GP",
    code3: "GLP",
    country_name: "Guadeloupe",
    country_number: "312",
  },
  { code: "GU", code3: "GUM", country_name: "Guam", country_number: "316" },
  {
    code: "GT",
    code3: "GTM",
    country_name: "Guatemala",
    country_number: "320",
  },
  { code: "GG", code3: "GGY", country_name: "Guernsey", country_number: "831" },
  { code: "GN", code3: "GIN", country_name: "Guinea", country_number: "324" },
  {
    code: "GW",
    code3: "GNB",
    country_name: "Guinea-Bissau",
    country_number: "624",
  },
  { code: "GY", code3: "GUY", country_name: "Guyana", country_number: "328" },
  { code: "HT", code3: "HTI", country_name: "Haiti", country_number: "332" },
  {
    code: "HM",
    code3: "HMD",
    country_name: "Heard Island and McDonald Islands",
    country_number: "334",
  },
  {
    code: "VA",
    code3: "VAT",
    country_name: "Holy See (the)",
    country_number: "336",
  },
  { code: "HN", code3: "HND", country_name: "Honduras", country_number: "340" },
  {
    code: "HK",
    code3: "HKG",
    country_name: "Hong Kong",
    country_number: "344",
  },
  { code: "HU", code3: "HUN", country_name: "Hungary", country_number: "348" },
  { code: "IS", code3: "ISL", country_name: "Iceland", country_number: "352" },
  { code: "IN", code3: "IND", country_name: "India", country_number: "356" },
  {
    code: "ID",
    code3: "IDN",
    country_name: "Indonesia",
    country_number: "360",
  },
  {
    code: "IR",
    code3: "IRN",
    country_name: "Iran (Islamic Republic of)",
    country_number: "364",
  },
  { code: "IQ", code3: "IRQ", country_name: "Iraq", country_number: "368" },
  { code: "IE", code3: "IRL", country_name: "Ireland", country_number: "372" },
  {
    code: "IM",
    code3: "IMN",
    country_name: "Isle of Man",
    country_number: "833",
  },
  { code: "IL", code3: "ISR", country_name: "Israel", country_number: "376" },
  { code: "IT", code3: "ITA", country_name: "Italy", country_number: "380" },
  { code: "JM", code3: "JAM", country_name: "Jamaica", country_number: "388" },
  { code: "JP", code3: "JPN", country_name: "Japan", country_number: "392" },
  { code: "JE", code3: "JEY", country_name: "Jersey", country_number: "832" },
  { code: "JO", code3: "JOR", country_name: "Jordan", country_number: "400" },
  {
    code: "KZ",
    code3: "KAZ",
    country_name: "Kazakhstan",
    country_number: "398",
  },
  { code: "KE", code3: "KEN", country_name: "Kenya", country_number: "404" },
  { code: "KI", code3: "KIR", country_name: "Kiribati", country_number: "296" },
  {
    code: "KP",
    code3: "PRK",
    country_name: "Korea (the Democratic People's Republic of)",
    country_number: "408",
  },
  {
    code: "KR",
    code3: "KOR",
    country_name: "Korea (the Republic of)",
    country_number: "410",
  },
  { code: "KW", code3: "KWT", country_name: "Kuwait", country_number: "414" },
  {
    code: "KG",
    code3: "KGZ",
    country_name: "Kyrgyzstan",
    country_number: "417",
  },
  {
    code: "LA",
    code3: "LAO",
    country_name: "Lao People's Democratic Republic (the)",
    country_number: "418",
  },
  { code: "LV", code3: "LVA", country_name: "Latvia", country_number: "428" },
  { code: "LB", code3: "LBN", country_name: "Lebanon", country_number: "422" },
  { code: "LS", code3: "LSO", country_name: "Lesotho", country_number: "426" },
  { code: "LR", code3: "LBR", country_name: "Liberia", country_number: "430" },
  { code: "LY", code3: "LBY", country_name: "Libya", country_number: "434" },
  {
    code: "LI",
    code3: "LIE",
    country_name: "Liechtenstein",
    country_number: "438",
  },
  {
    code: "LT",
    code3: "LTU",
    country_name: "Lithuania",
    country_number: "440",
  },
  {
    code: "LU",
    code3: "LUX",
    country_name: "Luxembourg",
    country_number: "442",
  },
  { code: "MO", code3: "MAC", country_name: "Macao", country_number: "446" },
  {
    code: "MG",
    code3: "MDG",
    country_name: "Madagascar",
    country_number: "450",
  },
  { code: "MW", code3: "MWI", country_name: "Malawi", country_number: "454" },
  { code: "MY", code3: "MYS", country_name: "Malaysia", country_number: "458" },
  { code: "MV", code3: "MDV", country_name: "Maldives", country_number: "462" },
  { code: "ML", code3: "MLI", country_name: "Mali", country_number: "466" },
  { code: "MT", code3: "MLT", country_name: "Malta", country_number: "470" },
  {
    code: "MH",
    code3: "MHL",
    country_name: "Marshall Islands (the)",
    country_number: "584",
  },
  {
    code: "MQ",
    code3: "MTQ",
    country_name: "Martinique",
    country_number: "474",
  },
  {
    code: "MR",
    code3: "MRT",
    country_name: "Mauritania",
    country_number: "478",
  },
  {
    code: "MU",
    code3: "MUS",
    country_name: "Mauritius",
    country_number: "480",
  },
  { code: "YT", code3: "MYT", country_name: "Mayotte", country_number: "175" },
  { code: "MX", code3: "MEX", country_name: "Mexico", country_number: "484" },
  {
    code: "FM",
    code3: "FSM",
    country_name: "Micronesia (Federated States of)",
    country_number: "583",
  },
  {
    code: "MD",
    code3: "MDA",
    country_name: "Moldova (the Republic of)",
    country_number: "498",
  },
  { code: "MC", code3: "MCO", country_name: "Monaco", country_number: "492" },
  { code: "MN", code3: "MNG", country_name: "Mongolia", country_number: "496" },
  {
    code: "ME",
    code3: "MNE",
    country_name: "Montenegro",
    country_number: "499",
  },
  {
    code: "MS",
    code3: "MSR",
    country_name: "Montserrat",
    country_number: "500",
  },
  { code: "MA", code3: "MAR", country_name: "Morocco", country_number: "504" },
  {
    code: "MZ",
    code3: "MOZ",
    country_name: "Mozambique",
    country_number: "508",
  },
  { code: "MM", code3: "MMR", country_name: "Myanmar", country_number: "104" },
  { code: "NA", code3: "NAM", country_name: "Namibia", country_number: "516" },
  { code: "NR", code3: "NRU", country_name: "Nauru", country_number: "520" },
  { code: "NP", code3: "NPL", country_name: "Nepal", country_number: "524" },
  {
    code: "NL",
    code3: "NLD",
    country_name: "Netherlands (the)",
    country_number: "528",
  },
  {
    code: "NC",
    code3: "NCL",
    country_name: "New Caledonia",
    country_number: "540",
  },
  {
    code: "NZ",
    code3: "NZL",
    country_name: "New Zealand",
    country_number: "554",
  },
  {
    code: "NI",
    code3: "NIC",
    country_name: "Nicaragua",
    country_number: "558",
  },
  {
    code: "NE",
    code3: "NER",
    country_name: "Niger (the)",
    country_number: "562",
  },
  { code: "NG", code3: "NGA", country_name: "Nigeria", country_number: "566" },
  { code: "NU", code3: "NIU", country_name: "Niue", country_number: "570" },
  {
    code: "NF",
    code3: "NFK",
    country_name: "Norfolk Island",
    country_number: "574",
  },
  {
    code: "MP",
    code3: "MNP",
    country_name: "Northern Mariana Islands (the)",
    country_number: "580",
  },
  { code: "NO", code3: "NOR", country_name: "Norway", country_number: "578" },
  { code: "OM", code3: "OMN", country_name: "Oman", country_number: "512" },
  { code: "PK", code3: "PAK", country_name: "Pakistan", country_number: "586" },
  { code: "PW", code3: "PLW", country_name: "Palau", country_number: "585" },
  {
    code: "PS",
    code3: "PSE",
    country_name: "Palestine, State of",
    country_number: "275",
  },
  { code: "PA", code3: "PAN", country_name: "Panama", country_number: "591" },
  {
    code: "PG",
    code3: "PNG",
    country_name: "Papua New Guinea",
    country_number: "598",
  },
  { code: "PY", code3: "PRY", country_name: "Paraguay", country_number: "600" },
  { code: "PE", code3: "PER", country_name: "Peru", country_number: "604" },
  {
    code: "PH",
    code3: "PHL",
    country_name: "Philippines (the)",
    country_number: "608",
  },
  { code: "PN", code3: "PCN", country_name: "Pitcairn", country_number: "612" },
  { code: "PL", code3: "POL", country_name: "Poland", country_number: "616" },
  { code: "PT", code3: "PRT", country_name: "Portugal", country_number: "620" },
  {
    code: "PR",
    code3: "PRI",
    country_name: "Puerto Rico",
    country_number: "630",
  },
  { code: "QA", code3: "QAT", country_name: "Qatar", country_number: "634" },
  {
    code: "MK",
    code3: "MKD",
    country_name: "Republic of North Macedonia",
    country_number: "807",
  },
  { code: "RO", code3: "ROU", country_name: "Romania", country_number: "642" },
  {
    code: "RU",
    code3: "RUS",
    country_name: "Russian Federation (the)",
    country_number: "643",
  },
  { code: "RW", code3: "RWA", country_name: "Rwanda", country_number: "646" },
  { code: "RE", code3: "REU", country_name: "Réunion", country_number: "638" },
  {
    code: "BL",
    code3: "BLM",
    country_name: "Saint Barthélemy",
    country_number: "652",
  },
  {
    code: "SH",
    code3: "SHN",
    country_name: "Saint Helena, Ascension and Tristan da Cunha",
    country_number: "654",
  },
  {
    code: "KN",
    code3: "KNA",
    country_name: "Saint Kitts and Nevis",
    country_number: "659",
  },
  {
    code: "LC",
    code3: "LCA",
    country_name: "Saint Lucia",
    country_number: "662",
  },
  {
    code: "MF",
    code3: "MAF",
    country_name: "Saint Martin (French part)",
    country_number: "663",
  },
  {
    code: "PM",
    code3: "SPM",
    country_name: "Saint Pierre and Miquelon",
    country_number: "666",
  },
  {
    code: "VC",
    code3: "VCT",
    country_name: "Saint Vincent and the Grenadines",
    country_number: "670",
  },
  { code: "WS", code3: "WSM", country_name: "Samoa", country_number: "882" },
  {
    code: "SM",
    code3: "SMR",
    country_name: "San Marino",
    country_number: "674",
  },
  {
    code: "ST",
    code3: "STP",
    country_name: "Sao Tome and Principe",
    country_number: "678",
  },
  {
    code: "SA",
    code3: "SAU",
    country_name: "Saudi Arabia",
    country_number: "682",
  },
  { code: "SN", code3: "SEN", country_name: "Senegal", country_number: "686" },
  { code: "RS", code3: "SRB", country_name: "Serbia", country_number: "688" },
  {
    code: "SC",
    code3: "SYC",
    country_name: "Seychelles",
    country_number: "690",
  },
  {
    code: "SL",
    code3: "SLE",
    country_name: "Sierra Leone",
    country_number: "694",
  },
  {
    code: "SG",
    code3: "SGP",
    country_name: "Singapore",
    country_number: "702",
  },
  {
    code: "SX",
    code3: "SXM",
    country_name: "Sint Maarten (Dutch part)",
    country_number: "534",
  },
  { code: "SK", code3: "SVK", country_name: "Slovakia", country_number: "703" },
  { code: "SI", code3: "SVN", country_name: "Slovenia", country_number: "705" },
  {
    code: "SB",
    code3: "SLB",
    country_name: "Solomon Islands",
    country_number: "090",
  },
  { code: "SO", code3: "SOM", country_name: "Somalia", country_number: "706" },
  {
    code: "ZA",
    code3: "ZAF",
    country_name: "South Africa",
    country_number: "710",
  },
  {
    code: "GS",
    code3: "SGS",
    country_name: "South Georgia and the South Sandwich Islands",
    country_number: "239",
  },
  {
    code: "SS",
    code3: "SSD",
    country_name: "South Sudan",
    country_number: "728",
  },
  { code: "ES", code3: "ESP", country_name: "Spain", country_number: "724" },
  {
    code: "LK",
    code3: "LKA",
    country_name: "Sri Lanka",
    country_number: "144",
  },
  {
    code: "SD",
    code3: "SDN",
    country_name: "Sudan (the)",
    country_number: "729",
  },
  { code: "SR", code3: "SUR", country_name: "Suriname", country_number: "740" },
  {
    code: "SJ",
    code3: "SJM",
    country_name: "Svalbard and Jan Mayen",
    country_number: "744",
  },
  { code: "SE", code3: "SWE", country_name: "Sweden", country_number: "752" },
  {
    code: "CH",
    code3: "CHE",
    country_name: "Switzerland",
    country_number: "756",
  },
  {
    code: "SY",
    code3: "SYR",
    country_name: "Syrian Arab Republic",
    country_number: "760",
  },
  { code: "TW", code3: "TWN", country_name: "Taiwan", country_number: "158" },
  {
    code: "TJ",
    code3: "TJK",
    country_name: "Tajikistan",
    country_number: "762",
  },
  {
    code: "TZ",
    code3: "TZA",
    country_name: "Tanzania, United Republic of",
    country_number: "834",
  },
  { code: "TH", code3: "THA", country_name: "Thailand", country_number: "764" },
  {
    code: "TL",
    code3: "TLS",
    country_name: "Timor-Leste",
    country_number: "626",
  },
  { code: "TG", code3: "TGO", country_name: "Togo", country_number: "768" },
  { code: "TK", code3: "TKL", country_name: "Tokelau", country_number: "772" },
  { code: "TO", code3: "TON", country_name: "Tonga", country_number: "776" },
  {
    code: "TT",
    code3: "TTO",
    country_name: "Trinidad and Tobago",
    country_number: "780",
  },
  { code: "TN", code3: "TUN", country_name: "Tunisia", country_number: "788" },
  { code: "TR", code3: "TUR", country_name: "Turkey", country_number: "792" },
  {
    code: "TM",
    code3: "TKM",
    country_name: "Turkmenistan",
    country_number: "795",
  },
  {
    code: "TC",
    code3: "TCA",
    country_name: "Turks and Caicos Islands (the)",
    country_number: "796",
  },
  { code: "TV", code3: "TUV", country_name: "Tuvalu", country_number: "798" },
  { code: "UG", code3: "UGA", country_name: "Uganda", country_number: "800" },
  { code: "UA", code3: "UKR", country_name: "Ukraine", country_number: "804" },
  {
    code: "AE",
    code3: "ARE",
    country_name: "United Arab Emirates (the)",
    country_number: "784",
  },
  {
    code: "GB",
    code3: "GBR",
    country_name: "United Kingdom of Great Britain and Northern Ireland (the)",
    country_number: "826",
  },
  {
    code: "UM",
    code3: "UMI",
    country_name: "United States Minor Outlying Islands (the)",
    country_number: "581",
  },
  {
    code: "US",
    code3: "USA",
    country_name: "United States of America (the)",
    country_number: "840",
  },
  { code: "UY", code3: "URY", country_name: "Uruguay", country_number: "858" },
  {
    code: "UZ",
    code3: "UZB",
    country_name: "Uzbekistan",
    country_number: "860",
  },
  { code: "VU", code3: "VUT", country_name: "Vanuatu", country_number: "548" },
  {
    code: "VE",
    code3: "VEN",
    country_name: "Venezuela (Bolivarian Republic of)",
    country_number: "862",
  },
  { code: "VN", code3: "VNM", country_name: "Viet Nam", country_number: "704" },
  {
    code: "VG",
    code3: "VGB",
    country_name: "Virgin Islands (British)",
    country_number: "092",
  },
  {
    code: "VI",
    code3: "VIR",
    country_name: "Virgin Islands (U.S.)",
    country_number: "850",
  },
  {
    code: "WF",
    code3: "WLF",
    country_name: "Wallis and Futuna",
    country_number: "876",
  },
  {
    code: "EH",
    code3: "ESH",
    country_name: "Western Sahara",
    country_number: "732",
  },
  { code: "YE", code3: "YEM", country_name: "Yemen", country_number: "887" },
  { code: "ZM", code3: "ZMB", country_name: "Zambia", country_number: "894" },
  { code: "ZW", code3: "ZWE", country_name: "Zimbabwe", country_number: "716" },
  {
    code: "AX",
    code3: "ALA",
    country_name: "Åland Islands",
    country_number: "248",
  },
  {
    code: "XX",
    code3: "BAD",
    country_name: "BAD BAD BAD",
    country_number: "000",
  },
];

const makeEmployeesArray = () => {
  return [
    {
      emp_id: "076a6bc0-fa0c-11eb-9a03-0242ac130003",
      first_name: "marcelina",
      last_name: "manuel",
      dob: "1992-01-31T08:00:00.000Z",
      age: "29",
      country: "PHL",
      date_modified: "2021-08-10T00:00:00.000Z",
    },
    {
      emp_id: "100e737a-fa0c-11eb-9a03-0242ac130003",
      first_name: "roger",
      last_name: "liu",
      dob: "1988-08-09T07:00:00.000Z",
      age: "33",
      country: "CHN",
      date_modified: "2021-08-10T00:00:00.000Z",
    },
    {
      emp_id: "16aa454c-fa0c-11eb-9a03-0242ac130003",
      first_name: "abbey",
      last_name: "livingston",
      dob: "1975-04-25T07:00:00.000Z",
      age: "46",
      country: "GBR",
      date_modified: "2021-08-10T00:00:00.000Z",
    },
    {
      emp_id: "1eddb3c0-fa0c-11eb-9a03-0242ac130003",
      first_name: "jason",
      last_name: "salazar",
      dob: "1981-11-04T08:00:00.000Z",
      age: "31",
      country: "ESP",
      date_modified: "2021-08-10T00:00:00.000Z",
    },
    {
      emp_id: "2607b45c-fa0c-11eb-9a03-0242ac130003",
      first_name: "trevor",
      last_name: "harrison",
      dob: "1986-10-10T07:00:00.000Z",
      age: "34",
      country: "USA",
      date_modified: "2021-08-10T00:00:00.000Z",
    },
    {
      emp_id: "28b87cb8-fa0c-11eb-9a03-0242ac130003",
      first_name: "ruth",
      last_name: "morgan",
      dob: "1993-12-07T08:00:00.000Z",
      age: "27",
      country: "USA",
      date_modified: "2021-08-10T00:00:00.000Z",
    },
  ];
};

const makeMaliciousEmployee = () => {
  const maliciousEmployee = {
    emp_id: "2973a2d6-cb18-11eb-b8bc-0242ac130003",
    first_name: 'BAD <script>alert("xss");</script>',
    last_name: 'BAD <script>alert("xss");</script>',
    country: "BAD",
    dob: "1991-06-01T00:00:00.000Z",
    age: "30",
    date_modified: "2021-08-10T00:00:00.000Z",
  };

  const expectedEmployee = {
    ...maliciousEmployee,
    emp_id: "2973a2d6-cb18-11eb-b8bc-0242ac130003",
    first_name: 'BAD &lt;script&gt;alert("xss");&lt;/script&gt;',
    last_name: 'BAD &lt;script&gt;alert("xss");&lt;/script&gt;',
    country: "BAD",
    dob: "1991-06-01T07:00:00.000Z",
    age: "30",
    date_modified: "2021-08-10T00:00:00.000Z",
  };
  return { maliciousEmployee, expectedEmployee };
};

const newEmployee = {
  first_name: "New",
  last_name: "Employee",
  country: "USA",
  dob: "1991-06-01T00:00:00.000Z",
  age: "30",
};

const updatedEmployee = {
  emp_id: "076a6bc0-fa0c-11eb-9a03-0242ac130003",
  first_name: "Updated",
  last_name: "Employee",
  country: "USA",
  dob: "1991-06-01T00:00:00.000Z",
  age: "30",
};

testIds = {
  employee: "076a6bc0-fa0c-11eb-9a03-0242ac130003",
};

module.exports = {
  countries,
  makeEmployeesArray,
  makeMaliciousEmployee,
  newEmployee,
  updatedEmployee,
  testIds,
};
